apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-app-fifth-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sentence-app
  template:
    metadata:
      labels:
        app: sentence-app
    spec:
      containers:
        - name: sentence-app
          image: us-central1-docker.pkg.dev/sentenceapp/sentenceappartifacts/sentenceapp:latest
          ports:
            - containerPort: 3000
