apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-app-deployment
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    type: RollingUpdate
  progressDeadlineSeconds: 600 
  selector:
    matchLabels:
      app: sentence-app
  template:
    metadata:
      labels:
        app: sentence-app
    spec:
      containers:
        - name: sentence-app
          image: gcr.io/sentenceapp/sentence-app
          ports:
            - containerPort: 3000
